params:
  huggingface_link: "allenai/OLMo-2-0425-1B-Instruct"
  model_name: "olmo2"
  
  pruning_method: ["sparsegpt", "wanda"]
  sparsity_ratio: [0.2, 0.5]
  sparsity_type: "unstructured" # 2:4, 4:8
  model_folder: "./out/" # need / in the end
  quantize_method: ["iq4xs", "q8_0"] # todo: gptqmodel gptq, awq

stages:
  setup:
    cmd: |
      git clone https://github.com/YouOnlyLive1ce/wanda.git
      wget https://huggingface.co/datasets/ggml-org/ci/resolve/main/wikitext-2-raw-v1.zip
      unzip wikitext-2-raw-v1.zip
      wget -q https://github.com/ggml-org/llama.cpp/releases/download/b7883/llama-b7883-bin-ubuntu-x64.tar.gz
      tar -xvzf llama-b7883-bin-ubuntu-x64.tar.gz
      mv llama-b7883 bin_llama
      git clone https://github.com/ggml-org/llama.cpp.git
    outs:
      - llama.cpp/quantize

  prune:
    for each: pruning_method
    for each: sparsity_ratio
    cmd: |
      git clone https://github.com/locuslab/wanda.git || true
      python ./wanda/main.py \
        --model ${huggingface_link} \
        --prune_method ${pruning_method} \
        --sparsity_ratio ${sparsity_ratio} \
        --sparsity_type ${sparsity_type} \
        --save ${model_folder}${model_name}/${sparsity_type}/ \
        --save_model ${model_folder}${model_name}/${sparsity_type}/
    deps: 
      - models/${huggingface_link}/base
    outs: 
      - ${model_folder}${model_name}/${sparsity_type}/

  convert_hf_to_gguf:
    cmd: |
      python llama.cpp/convert_hf_to_gguf.py ${model_folder}${model_name}/${sparsity_type}/ \
        --outfile ${model_folder}${model_name}_q16.gguf \
        --outtype f16
    deps:
      - ${model_folder}${model_name}/${sparsity_type}/
      - llama.cpp/convert_hf_to_gguf.py
    outs:
      - ${model_folder}${model_name}_q16.gguf

  quantize:
    for_each: quantize_method
    cmd: |
      ./bin_llama/llama-quantize \
        ${model_folder}${model_name}_q16.gguf \
        ${model_folder}${model_name}_${item}.gguf \
        ${item}
    deps:
      - ${model_folder}${model_name}_q16.gguf
      - bin_llama/quantize
    outs:
      - ${model_folder}${model_name}_${item}.gguf

  benchmark:
    for_each: quantize_method
    cmd: |
      python3 benchmark/benchmark.py \
        --model-name ${model_name}_${item} \
        --model-path ${model_folder}${model_name}_${item}.gguf \
    deps:
      - ${model_folder}${model_name}_${item}.gguf
    outs:
      - ./benchmark/benchmark_results/${model_name}_${item}.json